export const SET_CONFIG = 'SET_CONFIG'
export const SET_ABOUT = 'SET_ABOUT'
export const SET_EDUCATION = 'SET_EDUCATION'
export const SET_COURSE_NAMES = 'SET_COURSE_NAMES'
export const SET_WORK = 'SET_WORK'